### PR TITLE
config: added entries for judicial data load

### PR DESCRIPTION
**Pull request by shashank-rastogi**
### Change description ###
added entries for judicial data load

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

### CODE REVIEW

**Comment by timja** [comment]
@shashank-rastogi why do you need this for a data load application? what calls it?

**Comment by shashank-rastogi** [comment]
> @shashank-rastogi why do you need this for a data load application? what calls it?

@timja - health check was failing in ithc with 404 not found error -Microsoft-Azure-Application-Gateway/v2

**Comment by timja** [comment]
> > @shashank-rastogi why do you need this for a data load application? what calls it?
> 
> @timja - health check was failing in ithc with 404 not found error -Microsoft-Azure-Application-Gateway/v2

that doesn't answer the question?
Shouldn't a data load be a scheduled job?

**Comment by shashank-rastogi** [comment]
> > > @shashank-rastogi why do you need this for a data load application? what calls it?
> > 
> > 
> > @timja - health check was failing in ithc with 404 not found error -Microsoft-Azure-Application-Gateway/v2
> 
> that doesn't answer the question?
> Shouldn't a data load be a scheduled job?

@timja  - it is.. we are currently using spring scheduler... and are working on to change this to a kubernetes scheduler job

**Pull request merged**
